# Generated by Django 3.2.7 on 2021-10-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [

    ]
