# Generated by Django 3.2.7 on 2021-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211001_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='englishWord',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='words',
            name='mandarinWord',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='words',
            name='pinyinWord',
            field=models.TextField(default=''),
        ),
    ]
